version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build-and-test:
    macos:
      xcode: "14.2.0"
      #resource_class: macos.x86.medium.gen2
    shell: /bin/bash --login -eo pipefail

    steps:
      - checkout
      # Gems cache
      - restore_cache:
           key: 1-gems-{{ checksum "Gemfile" }}

      - run: 
          name: Check Gemfile
          command:  bundle check || bundle install

      - save_cache:
           key: 1-gems-{{ checksum "Gemfile" }}
           paths:
             - vendor/bundle
             - Gemfile.lock
             - .bundle

      # Build the app and run tests
      - run:
          name: Execute unit tests with fastlane
          command: |
            bundle exec fastlane unit_tests
      - codecov/upload

      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test